### ISSUE TITLE
Tooltip positioning incorrect in Power BI Desktop App

### ISSUE THREAD

**Issue by willyt150** [Microsoft/powerbi-visuals-utils-tooltiputils#10]
The tooltip positioning is correct in powerbi.com using Chrome, Edge, and IE (haven't checked any other browsers), but it is way off in the Power BI Desktop App.

Here are a few screenshots showing the issue. I've also created a very simple visual with a single SVG circle, and it has the exact same issue. [Here](https://drive.google.com/file/d/0BwBi8pB5QQvZbV9hMnNVeXg2Q1k/view?usp=sharing)

 Any ideas on why the positioning is so far off?

Thanks!

**Powerbi.com in Chrome**
![Powerbi.com in Chrome](https://cloud.githubusercontent.com/assets/1190775/24425867/85500974-13ba-11e7-91fd-d34aea5ab84d.png)

**Power BI Desktop**
![Power BI Desktop](https://cloud.githubusercontent.com/assets/1190775/24425993/ef150e2c-13ba-11e7-895a-7d58a1f8f8f9.png)

**Very simple circle Power BI Desktop**
![Very simple circle Power BI Desktop](https://cloud.githubusercontent.com/assets/1190775/24427726/ddc31492-13c0-11e7-8469-2d25e0d0e0bf.png)

**Comment by willyt150** [comment]
If i go into **Focus mode** for the visual then the tooltips position correctly.

**Comment by tosta1989** [comment]
Hi Willy,

Iv'e just tested the visual you created + other custom visuals and the tooltip positioning seems to be correct. 

did you install the latest release of Power BI desktop?
we just recently fixed the tooltip positioning problem, so older versions of Power BI might still have this issue. 

Thanks,
Idan

**Comment by willyt150** [comment]
Hello Idan,

You are correct. I had version **2.44.4675.521 64-bit (March 2017)**. I just downloaded and installed the latest from powerbi.com and version **2.45.4704.442 64-bit (April 2017)** has fixed this issue.

Thanks!
