### ISSUE TITLE
d3 cannot find namespace error for TooltipService 

### ISSUE THREAD

**Issue by supermaker** [Microsoft/powerbi-visuals-utils-tooltiputils#12]
Hi,
I created new powerbi custom visual project. After i added this tooltip package, but not working. I think general a bug.
this screen capture [Link](http://supermaker.0fees.net/dosyalar/Ekran%20Al%C4%B1nt%C4%B1s%C4%B1.PNG)

**Comment by uve** [comment]
Hello @supermaker, have you tried to run **npm install** command?

**Comment by supermaker** [comment]
Hi @uve;
Yes I tried npm install. But i taking still same error.

**Comment by uve** [comment]
@supermaker, please send your source code to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>, we'll check it.

**Comment by supermaker** [comment]
I sended my source code. Thanks for support. I am waiting with hope. :D

**Comment by uve** [comment]
@supermaker,
To compile your project, you have to add D3 types to your packages.json file and run **npm install** command again.
Sample:
https://github.com/Microsoft/PowerBI-visuals-ChicletSlicer/blob/master/package.json#L23-L26

**Comment by supermaker** [comment]
Hi @uve;
But this lines have in my source code.

**Comment by uve** [comment]
@supermaker
It’s test/node_modules/powerbi-visual-utils-tooltiputils/package.json.
You don’t need to change this npm package.
Instead of that, you need modify test/package.json file in your project directory.

**Comment by supermaker** [comment]
Yesss it is running. Thank you very much.  
Sorry my misunderstanding. And thank you for your fast answer.
