### ISSUE TITLE
Values displaying in tool-tip/visualization are incorrect

### ISSUE THREAD

**Issue by psrinivasamaniprabhakar** [Microsoft/powerbi-visuals-utils-tooltiputils#24]
Hi,

Values displaying in Visualization are incorrect.  For example, Total I have 2000 records, in Root node it is showing only 400 value.  Please look into this asap

**Comment by helen508light** [comment]
Hi, @psrinivasamaniprabhakar 
Thanks for your feedback.

Could you send your .pbix report reproducing this issue to pbicvsupport.com?

**Comment by helen508light** [comment]
@psrinivasamaniprabhakar 
your issue is related to the visual you had used
Which one you had used?
