### ISSUE TITLE
Always top show until click to close button

### ISSUE THREAD

**Issue by metinsevindik** [microsoft/powerbi-visuals-utils-tooltiputils#25]
Hi,
Is it possible tooltips always top show until click to close button?
Thank you.

**Comment by helen508light** [comment]
Hi @metinsevindik 

Thank you for feedback!
We'll consider your suggestion in the next versions of the visual.
Please note thst source code is public, feel free to fork and modify if for your needs.

**Comment by helen508light** [comment]
This suggestion has been implemented in 2.3.0 version
