### ISSUE TITLE
Property 'tooltip' does not exist on type 'typeof utils'.

### ISSUE THREAD

**Issue by jamesabrook** [Microsoft/powerbi-visuals-utils-tooltiputils#26]
Hi There,

I've followed the [installation guide](https://github.com/Microsoft/powerbi-visuals-utils-tooltiputils/blob/master/docs/usage/installation-guide.md) but when I try and import the tooltip I get a compile error "Property 'tooltip' does not exist on type 'typeof utils'."  Is this guide out-dated now?

Thanks

**Comment by helen508light** [comment]
Hi @jamesabrook 
which version of tooltiputis did you use? And with which powerbi-visuals-api and powerbi-visuals-tools versions?

**Comment by jamesabrook** [comment]
Hi Helen,

The version of tooltiputils is 1.1.1 along with powerbi-visual-tools 2.3.0.  How do I check the powerbi-visuals-api version or is that the same as powerbi-visual-tools?

Thanks!

**Comment by helen508light** [comment]
@jamesabrook 
if you use it for custom visuals, api version is always written in pbiviz.json file is "apiVersion" section.
This error may be caused your tsconfig.json or pbiviz.json wrong configuration. Did you write     "node_modules/powerbi-visuals-utils-tooltiputils/lib/index.d.ts" into tsconfig/json "files" section ?

For example, there  tsconfig.json and pbiviz.json configuration from https://github.com/Microsoft/powerbi-visuals-Gantt
![image](https://user-images.githubusercontent.com/12563593/54929851-41eed200-4f27-11e9-876c-78506039702b.png)
![image](https://user-images.githubusercontent.com/12563593/54929899-5501a200-4f27-11e9-97f4-7d2c333bcb40.png)

**Comment by jamesabrook** [comment]
@helen508light - yes, I have entered the references as you mention above (pictures below).  I guess the error must be caused from the fact that I have apiVersion 2.3.0.  

![pbiviz json](https://user-images.githubusercontent.com/35072324/54932979-b4ee4d80-4f13-11e9-944b-8cdcdbe3e3af.png)
![tsconfig json](https://user-images.githubusercontent.com/35072324/54932982-b61f7a80-4f13-11e9-82b4-274045527d53.png)

**Comment by helen508light** [comment]
@jamesabrook

I installed apiVersion 2.3.0 with powerbi-tools and tooltip utils as you have mentioned, but there no errors.
Could you upload your project in public github repo or send to powerbi support pbicvsupport.com ?

**Comment by jamesabrook** [comment]
Apologies @helen508light for the late response.  I installed the plug in again on a different machine and it worked so not sure what was wrong first time around!  Thanks again for your help.
