### ISSUE TITLE
Struggling to add tooltips. `mouseEvent` is null.

### ISSUE THREAD

**Issue by zidhuss** [microsoft/powerbi-visuals-utils-tooltiputils#31]
Hi. I'm trying to add tooltips to the custom visuals. The docs appear to be out of date. Especially the [usage guide](https://github.com/microsoft/powerbi-visuals-utils-tooltiputils/blob/master/docs/api/tooltipservice.md).

I've managed to import it despite the examples shown on that page. Right now when I'm attempting to show a tooltip, I'm met with with `mouseEvent is null` error coming from the console.

This error looks to be coming from https://github.com/microsoft/powerbi-visuals-utils-tooltiputils/blob/fc12ca5232ab318352a27e7d00b36c56b964c969/src/tooltipService.ts#L227

Any help would be appreciated.

Thanks

**Comment by danieleperilli** [comment]
I had the same problem. I solved by migrating the D3.js library to the v5.

**Comment by zidhuss** [comment]
Thanks. I'll give that a go.

It seems strange that there is no mention of this in the documentation. Even the official documentation recommends installing d3 v3.5: https://docs.microsoft.com/en-gb/power-bi/developer/custom-visual-develop-tutorial#adding-visual-elements.

**Comment by zidhuss** [comment]
Upgrading to v5 does seem to solve the issue. Thanks @danieleperilli .

Documentation should be changed to make the next person aware of this issue.

**Comment by helen508light** [comment]
Hi all
Now documentation update is in progress
